title:              Sportzguru
email:              rgujar6335@gmail.com
description:        All about sports
author:             Neel Gujar
baseurl:            ""
url:                "https://blackrockdigital.github.io"

# Social Profiles
twitter_username:   rahulgujar

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
